const menu = {
home:{
    title:'主页',
    icon:'home',
    child:{
      info:{
        title:'信息概览',
        icon:'dashboard'
      },
      system:{
        title:'系统概况',
        icon:'pc'
      },
      setting:{
        title:'系统设置',
        icon:'setting'
      },
      count:{
        title:'访问统计',
        icon:'line-chart'
      },
    }
  },
  order:{
    title:'家谱',
    icon:'order',
    child:{
      tel:{
        title:'电话订单',
        icon:'order-tel'
      },
      web:{
        title:'网络订单',
        icon:'order-web'
      },
      setting:{
        title:'订单管理',
        icon:'order-setting'
      },
      count:{
        title:'订单统计',
        icon:'order-count'
      },
    }
  },
  quan:{
    title:'礼券',
    icon:'quan',
    child:{
      add:{
        title:'礼券生成',
        icon:'quan-add'
      },
      setting:{
        title:'礼券管理',
        icon:'quan-setting'
      },
      configure:{
        title:'礼券配置',
        icon:'quan-configure'
      },
      user:{
        title:'礼券客户',
        icon:'quan-user'
      },
      count:{
        title:'礼券统计',
        icon:'quan-count'
      },
    }
  },
  quan:{
    title:'产品',
    icon:'product',
    child:{
      category:{
        title:'产品分类',
        icon:'product-category'
      },
      setting:{
        title:'产品管理',
        icon:'product-setting'
      },
      material:{
        title:'产品素材',
        icon:'product-material'
      },
      count:{
        title:'产品统计',
        icon:'product-count'
      },
    }
  },
  stock:{
    title:'库存',
    icon:'stock',
    child:{
      order:{
        title:'采购清单',
        icon:'stock-order'
      },
      in:{
        title:'产品入库',
        icon:'stock-in'
      },
      out:{
        title:'产品出库',
        icon:'stock-out'
      },
      count:{
        title:'库存统计',
        icon:'stock-count'
      },
    }
  },
  express:{
    title:'物流',
    icon:'express',
    child:{
      area:{
        title:'物流区域',
        icon:'express-area'
      },
      setting:{
        title:'物流设置',
        icon:'express-setting'
      },
      search:{
        title:'物流查询',
        icon:'express-search'
      },
      count:{
        title:'物流统计',
        icon:'express-count'
      },
    }
  },
  safe:{
    title:'安全',
    icon:'safe',
    child:{
      user:{
        title:'账户管理',
        icon:'user-setting'
      },
      role:{
        title:'角色管理',
        icon:'user-role'
      },
      auth:{
        title:'权限设置',
        icon:'user-auth'
      },
      database:{
        title:'数据管理',
        icon:'database-setting'
      },
      data:{
        title:'帐套管理',
        icon:'data'
      },
    }
  },
  message:{
    title:'信息',
    icon:'message',
    child:{
      notice:{
        title:'公告信息',
        icon:'comment'
      },
      chat:{
        title:'留言信息',
        icon:'chat'
      },
      log:{
        title:'日志信息',
        icon:'ask'
      },
    }
  },
  content:{
    title:'内容',
    icon:'news',
    child:{
      link:{
        title:'内容导航',
        icon:'list'
      },
      list:{
        title:'内容列表',
        icon:'item'
      },
      log:{
        title:'内容组件',
        icon:'bill'
      },
    }
  }
}